parameters:

  tinymce.class:               dmTinyMce  
  
services:

  tinymce:
    class:                      %tinymce.class%
    shared:                     true
    arguments:                  [@helper]  